### ISSUE TITLE
update RegexpHeader to accept new copyright header

### ISSUE THREAD

**Issue by keturn** [MovingBlocks/TeraConfig#11]
New header text as defined here: https://github.com/MovingBlocks/Terasology/blob/02bcf8015cc82031277a13d745fb0cee984e1481/.idea/copyright/Terasology_Foundation.xml#L5

and currently we've got it using line-comment syntax `//` instead of block-comment `/* */` to spare us the extra opening and closing lines.

**Comment by Cervator** [comment]
We could probably add that here, bump version, and make Terasology use the very latest. Previously I've just "built" a new zip and published it from a manual workspace with a Artifactory credential set up.

Other projects use the config too, but would stay on the old version till ready. TerasologyLauncher is the main other one, maybe CrashReporter? And DestSol _should_ use it if it isn't yet.

**Comment by skaldarnar** [comment]
This repo has Github actions enabled to build and release stuff 😉  So just doing the change and pushing a tag alongside will run the action, build the zip and publish to Artifactory.

**Comment by keturn** [comment]
fixed by #12
