### ISSUE TITLE
please release changes

### ISSUE THREAD

**Issue by soloturn** [MovingBlocks/TeraConfig#21]
can you please create a release o the changes can be used?

**Comment by jdrueckert** [comment]
I already created a new tag as can be seen from https://github.com/MovingBlocks/TeraConfig/releases/tag/v2.0.0
However, the release action currently fails to authenticate with artifactory as can be seen from https://github.com/MovingBlocks/TeraConfig/actions/runs/6370073813/job/17290860631#step:4:42

**Comment by BenjaminAmos** [comment]
A release should have been pushed by https://github.com/MovingBlocks/TeraConfig/actions/workflows/release.yml but the GitHub action failed. The [`v2.0.0`](https://github.com/MovingBlocks/TeraConfig/releases/tag/v2.0.0) tag does exist though, so the changes are technically released now. The release zip still needs to be published, which could take a bit longer whilst the action is being fixed.

**Comment by BenjaminAmos** [comment]
(My comment just now was written before https://github.com/MovingBlocks/TeraConfig/issues/21#issuecomment-1742094886 - I just submitted it before I noticed the other one.)

**Comment by jdrueckert** [comment]
Action fixed, release should be available now.
