### ISSUE TITLE
codeMetrics

### ISSUE THREAD

**Issue by LiushuiXiaoxia** [MovingBlocks/TeraConfig#4]
你好，我正在做这个一样的东西，怎么样可以读取plugin.jar中的xml文件？

how to config checkstyle's configFile, when default config file is in plugin.jar.

**Comment by LiushuiXiaoxia** [comment]
我从这边得到的信息。

https://discuss.gradle.org/t/how-can-i-read-setup-resources-from-plugin-jar/13274/5

**Comment by Cervator** [comment]
Not sure if you're asking about anything Terasology specific, which is what this repo is for. We aren't affiliated with Gradle the project itself :-)

One of us simply built a zip file with a few metrics config files then published it to our Artifactory. Then we depend on that zip file in our build scripts. See https://github.com/MovingBlocks/Terasology/blob/develop/build.gradle#L80 for instance.
